---
- job:
    name: logreduce-tests
    parent: base
    description: The logreduce regression tests suite
    run: playbooks/logreduce-tests.yaml
    required-projects:
      - logreduce
      - logreduce-tests
    nodeset:
      nodes:
        - name: container
          label: pod-fedora-31

- project:
    name: logreduce
    check:
      jobs:
        - logreduce-tests
        - tox-pep8:
            nodeset:
              nodes:
                - name: testrunner
                  label: pod-fedora-31
        - tox-py37:
            nodeset:
              nodes:
                - name: testrunner
                  label: pod-fedora-31
    gate:
      jobs:
        - logreduce-tests
        - tox-pep8:
            nodeset:
              nodes:
                - name: testrunner
                  label: pod-fedora-31
        - tox-py37:
            nodeset:
              nodes:
                - name: testrunner
                  label: pod-fedora-31
    release:
      jobs:
        - upload-pypi
