# Update from https://github.com/logreduce/logreduce/releases
logreduce_version: 0.8.4

# Set include/exclude file list
logreduce_config: null

_has_config: "{{ logreduce_config | default(false) }}"
_model_hash: "{% if _has_config %}-{{ logreduce_config | hash('md5') }}{% endif %}"
_model_path: "{{ logreduce_tmp_dir }}/model.bin"

# Change this to a local location with a folder per web's version.
logreduce_web_url: null

# Set this to true to run logreduce
logreduce_optin: false

# How old (in days) can a built model be used
logreduce_model_age: 7

# Enable logreduce debug logs
logreduce_debug: false

# Maximum runtime in seconds
logreduce_max_run_time: 900

# Zuul API to query for baseline
logreduce_zuul_web: https://softwarefactory-project.io/zuul/
logreduce_model_store_url: https://softwarefactory-project.io/logs/classifiers

# Local path
logreduce_tmp_dir: "{{ ansible_env.HOME }}/.logreduce"
